### ISSUE TITLE
Encrypted payload

### ISSUE THREAD

**Issue by cristoforocervino** [giu1io/homebridge-ankuoo-rec-switch#1]
Hi,

I'm having troubles finding encrypted payload.
I sniff the on/off package that the Rec App is sending to turn on and off the switch.
Besides, the encrypted payload result to be different for each package.
I never found the same payload even if I tried multiple times to turn the switch on and off.

What am I doing wrong? I attach a screen.

![img_8354 copia](https://cloud.githubusercontent.com/assets/25152680/25751257/a06a0fbc-31b4-11e7-8881-609937dd355a.jpg)

Thanks in advance,
Cristoforo

**Comment by giu1io** [comment]
Hi, 
The encrypted payload changes every time because there's a counter inside the payload. You can just use any of those payloads, it doesn't matter which one, the switch will accept any of them. ON payloads are different from OFF payloads obviously and are not interchangeable.

**Comment by familyofharris** [comment]
i have tried all the payloads that wireshark give me, the icon shows the status of the switch but when pressed it doesnt active or deactive the relay? can anybody help please..
