### ISSUE TITLE
how to add two switch config??

### ISSUE THREAD

**Issue by OctoberHub** [giu1io/homebridge-ankuoo-rec-switch#3]
hi,  This config it's ok???

"accessories": [
		{
			"accessory": "AnkuooRecSwitch",
			"name": "Switch number one",
			"ip": "192.168.XXX.XXX",
			"mac": "ac:cf:XX:XX:XX:XX",
			"onCode": "9464c0499574484f04a29367XXXXXXXX", 
			"offCode": "fd344f402a3f6299b53010XXXXXXXXXX"

                         "accessory": "AnkuooRecSwitch",
			"name": "Switch number two",
			"ip": "192.168.XXX.XXX",
			"mac": "bb:cf:XX:XX:XX:XX",
			"onCode": "dfsafas4c0499574484f04a29367XXXXXXXX", 
			"offCode": "ddfadxxxxxxxxxxxxxxxxxxxxxxxxx"
		}

**Comment by giu1io** [comment]
It’s hard to tell because I don’t see it formatted properly but it should be something like:
```
{
   "accessories":[
      {
         "accessory":"AnkuooRecSwitch",
         "name":"Switch number one",
         "ip":"192.168.XXX.XXX",
         "mac":"ac:cf:XX:XX:XX:XX",
         "onCode":"9464c0499574484f04a29367XXXXXXXX",
         "offCode":"fd344f402a3f6299b53010XXXXXXXXXX"
      },
      {
         "accessory":"AnkuooRecSwitch",
         "name":"Switch number two",
         "ip":"192.168.XXX.XXX",
         "mac":"ac:cf:XX:XX:XX:XX",
         "onCode":"9464c0499574484f04a29367XXXXXXXX",
         "offCode":"fd344f402a3f6299b53010XXXXXXXXXX"
      }
   ]
}
```
