### ISSUE TITLE
Status and message

### ISSUE THREAD

**Issue by jemesse** [giu1io/homebridge-ankuoo-rec-switch#5]
After following your precious tutorial, now I can have the status of the switch correctly show on HomeKit but I can't change it.
have you any other tips/suggestion?

**Comment by giu1io** [comment]
Which firmware version are you running? I have been hearing from people that it's not working for them, and I am afraid that they changed something in newer firmware revisions of the switch. Mine is on ```1.3103```, what version is yours on?
