### ISSUE TITLE
Homebridge is not sending the Packets

### ISSUE THREAD

**Issue by smnmsr** [giu1io/homebridge-ankuoo-rec-switch#7]
Hi

First of all: thanks for this plugin! i've been searching too long now!

I've got a similar Product. Actually it is branded by another company but in facts it's the exactly same Ankuoo-Rec-Switch.

I managed to sniff the on- and off-Codes with wireshark. The packet shows up in the way you described it. Then i configured the configuration.json exactly how you did it - just with the codes of my device.

The Device then showed up in the Homekit-App, but didn't work.

Whenever i turn it off or on nothing happens and there is also no Packet sent. 

Do you have an idea, what the problem could be?

cheers

**Comment by giu1io** [comment]
Hi,
when you say
> Whenever i turn it off or on nothing happens and there is also no Packet sent.

what do you mean exactly with "no packet sent"? Did you check the network traffic from your homebridge device and you saw that no packet is being sent? Or the packet is being sent but it's not working?
